### ISSUE TITLE
Using IAM Roles

### ISSUE THREAD

**Issue by marcieltorres** [Wattpad/kube-sqs-autoscaler#13]
Hi guys, I'm trying to use this project with `IAM Roles`, but this error happens:

`Failed to get SQS messages: Failed to get messages in SQS: NoCredentialProviders: no valid providers in chain. Deprecated. \in\For verbose messaging see aws.Config.CredentialsChainVerboseErrors` 

Any idea?

I'm using [kube2iam](https://github.com/jtblin/kube2iam) to use the IAM Roles and my deployment is like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {my-namespace}
  name: my-scaler
  labels:
    app: my-scaler
    env: prod
    process: worker
    product: my-product
    deploy: my-scaler
    release: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-scaler
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::{account}:role/{iam_role_name}
      labels:
        app: my-scaler
    spec:
      containers:
      - name: my-scaler
        image: wattpad/kube-sqs-autoscaler:v1.2.1
        command:
          - /kube-sqs-autoscaler
          - --sqs-queue-url=$(QUEUE_URL)  # required
          - --kubernetes-deployment={my-deployment} # required
          - --kubernetes-namespace={my_namespace} # optional
          - --aws-region=$(AWS_DEFAULT_REGION) #required
          - --poll-period=1m # optional
          - --scale-down-cool-down=1m # optional
          - --scale-up-cool-down=3m # optional
          - --scale-up-messages=10000 # optional
          - --scale-down-messages=5000 # optional
          - --max-pods=10 # optional
          - --min-pods=1 # optional
        env:
          - name: AWS_DEFAULT_REGION
            value: sa-east-1
          - name: QUEUE_URL
            value: {my_queue}
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "100m"
        volumeMounts:
          - name: ssl-certs
            mountPath: /etc/ssl/certs/ca-certificates.crt
            readOnly: true
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-certificates.crt"
```

Thanks
